# Generated by Django 5.2 on 2025-07-23 11:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('desc', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('target', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Farbe muss ein 6-stelliger Hex-Code sein, z.B. #FF0000', regex='^#([A-Fa-f0-9]{6})$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=40)),
                ('desc', models.TextField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='module_3d_libary.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('desc', models.TextField(max_length=200)),
                ('tag_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='module_3d_libary.tag_group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=40)),
                ('version', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Version muss eine valide Versionsbezeichnung sein, z.B. 1.1', regex='^([0-9]{1}.[0-9]{2}$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/img')),
                ('fc_file', models.FileField(blank=True, null=True, upload_to='uploads/fc_file')),
                ('stl_file', models.FileField(upload_to='uploads/stl_file')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Variants', to='module_3d_libary.parts')),
                ('printprofil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module_3d_libary.printprofil')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
