# Generated by Django 5.2 on 2025-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_3d_libary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='tags',
            field=models.ManyToManyField(related_name='parts', to='module_3d_libary.tag'),
        ),
    ]
