# Generated by Django 5.2 on 2025-07-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_3d_libary', '0002_parts_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parts',
            new_name='Part',
        ),
        migrations.RenameModel(
            old_name='PrintProfil',
            new_name='Print_Profil',
        ),
        migrations.RenameModel(
            old_name='Variants',
            new_name='Variant',
        ),
    ]
