# Generated by Django 5.2 on 2025-08-10 08:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_3d_libary', '0003_rename_parts_part_rename_printprofil_print_profil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='notice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='fc_file',
            field=models.FileField(blank=True, null=True, upload_to='3d_libary/uploads/fc_file', validators=[django.core.validators.FileExtensionValidator(['FCStd'])]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='3d_libary/uploads/img', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='module_3d_libary.part'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='stl_file',
            field=models.FileField(upload_to='3d_libary/uploads/stl_file', validators=[django.core.validators.FileExtensionValidator(['stl', '3mf'])]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='version',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Version muss eine valide Versionsbezeichnung sein, z.B. 1.1', regex='^\\d+\\.\\d{1,2}$')]),
        ),
    ]
